### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Sarah-C** [lightspeedgraphics/iesna#1]
Thanks for writing this!
I've dropped it onto CodePen for people who may want to look at the demo without the Node compiler.

https://codepen.io/SarahC/pen/jOGNwMN?editors=1010

I wonder if I it would be worth me writing an editor that shows the light output as a simple 360 x 180 bitmap, for artists to generate their own IES files.
The ones online are relatively complex - the user adds horizontal/vertical slices, and manipulates them in layers... to me I think something that abstracts all that away, and provides the user with a simple canvas and "light paintbrush" would make custom IES files super simple to produce. =)

The simplest process to making the IES would then be serialise the (double resolution) 720 x 360 image into a large IES file...  probably 1MB or more... a more complex process could look for areas of change and just write the angles and brightness's of layers/segments/angles that repeat - just how the IES files already do.

**Comment by richard-viney** [comment]
Great to hear someone's found this library useful! The CodePen is a neat demo, thanks for doing that.

If you're keen to build other tools on top of this library then please go right ahead. It's actually no longer being used by the company that originally did the development, but I'm happy to keep maintaining it.
